#!/usr/bin/env node
// The counterpart to `pnpm install`: removes build outputs and tool caches across
// every workspace package, plus Metro/Expo's caches outside the repo (they live in
// $TMPDIR, so `rm -rf` inside the repo never reaches them).
//
// Everything removed here is gitignored and regenerated by a build, an install or a
// dev server — the script refuses to touch anything outside the repo root or $TMPDIR,
// and never walks into a `node_modules` it is not deleting wholesale.
//
//   pnpm clean              build outputs + caches (node_modules and ios/android kept)
//   pnpm clean --native     also the generated ios/ and android/ projects (CNG rebuilds them)
//   pnpm clean --deps       also every node_modules — `pnpm install` afterwards
//   pnpm clean --store      also `pnpm store prune` (global pnpm store, machine-wide)
//   pnpm clean --all        all of the above, plus expo's generated type declarations
//   pnpm clean --dry-run    print what would go, delete nothing

import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tmpRoot = fs.realpathSync(os.tmpdir());

const flags = new Set(process.argv.slice(2));
const has = (...names) => names.some((n) => flags.has(n));

if (has("--help", "-h")) {
  console.log(`pnpm clean — remove build outputs and caches across every workspace package.

  (no flags)   dist/, .expo/cache, node_modules/.cache, *.tsbuildinfo, Metro's $TMPDIR caches
  --gradle     also android's build state (.gradle, build/, app/.cxx) — keeps the project
  --native     also apps/mobile/ios and apps/mobile/android outright (CNG regenerates both)
  --deps       also every node_modules — run pnpm install afterwards
  --store      also pnpm store prune (machine-wide pnpm store)
  --all        all of the above, plus expo's generated type declarations
  --dry-run    print what would be removed, delete nothing

~/.gradle is never touched: it is machine-wide, shared with every other Android
project, and re-downloading it costs far more than the disk it holds. Clear it by
hand if you really mean to.`);
  process.exit(0);
}

const all = has("--all");
const dryRun = has("--dry-run", "-n");
const withNative = all || has("--native");
const withGradle = all || withNative || has("--gradle");
const withDeps = all || has("--deps");
const withStore = all || has("--store");

const unknown = [...flags].filter(
  (f) => !["--all", "--dry-run", "-n", "--gradle", "--native", "--deps", "--store"].includes(f),
);
if (unknown.length > 0) {
  console.error(`clean: unknown option ${unknown.join(", ")} — try --help`);
  process.exit(1);
}

// Ask pnpm for the workspace rather than re-encoding pnpm-workspace.yaml's globs here;
// a package added under apps/ or packages/ is then cleaned without touching this file.
function workspacePaths() {
  try {
    const out = execFileSync("pnpm", ["list", "-r", "--depth", "-1", "--json"], {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return JSON.parse(out).map((pkg) => pkg.path);
  } catch {
    // pnpm missing or node_modules already gone mid-clean — fall back to the globs.
    return [
      repoRoot,
      ...["apps", "packages"].flatMap((group) =>
        fs
          .readdirSync(path.join(repoRoot, group), { withFileTypes: true })
          .filter((e) => e.isDirectory())
          .map((e) => path.join(repoRoot, group, e.name)),
      ),
    ].filter((dir) => fs.existsSync(path.join(dir, "package.json")));
  }
}

// Per package, relative to its root. Missing entries are skipped silently.
const PACKAGE_TARGETS = [
  "dist", // tsc/nest output: shared, db, api
  "web/dist", // admin's Vite SPA, if anyone ever runs a build there
  ".expo/cache", // Metro + eslint caches (.expo/types is generated *types*, see below)
  "node_modules/.cache",
  "node_modules/.vite",
  ".eslintcache",
];

const targets = [];
const seen = new Set();
const add = (abs, note) => {
  const resolved = path.resolve(abs);
  if (seen.has(resolved) || !fs.existsSync(resolved)) return;
  seen.add(resolved);
  targets.push({ abs: resolved, note });
};

for (const pkg of workspacePaths()) {
  for (const rel of PACKAGE_TARGETS) add(path.join(pkg, rel));
  // *.tsbuildinfo sits next to the tsconfig that produced it, under whatever name.
  for (const entry of fs.readdirSync(pkg)) {
    if (entry.endsWith(".tsbuildinfo")) add(path.join(pkg, entry));
  }
  if (withDeps) add(path.join(pkg, "node_modules"), "reinstall required");
}

// Metro keeps its transform cache and haste map in $TMPDIR, which is why a bundle can
// stay stale after every in-repo cache is gone (see `expo start --clear`).
const TMP_CACHE_PREFIXES = ["metro-", "haste-map-", "react-native-packager-cache-"];
try {
  for (const entry of fs.readdirSync(tmpRoot)) {
    if (TMP_CACHE_PREFIXES.some((prefix) => entry.startsWith(prefix))) {
      add(path.join(tmpRoot, entry), "metro");
    }
  }
} catch {
  // $TMPDIR unreadable — the in-repo clean is still worth doing.
}

if (withGradle) {
  // Android's build state, without deleting the generated project the way --native does.
  // `app/.cxx` is the NDK/CMake output and dwarfs everything else in the repo — it is the
  // reason this tier exists, since reaching it otherwise costs a full prebuild.
  // The Gradle *user home* (~/.gradle, incl. its 300MB+ dependency cache) is deliberately
  // out of scope: it is machine-wide and shared with every other Android project here.
  for (const rel of [".gradle", "build", ".kotlin", "app/build", "app/.cxx"]) {
    add(path.join(repoRoot, "apps/mobile/android", rel), "gradle rebuild");
  }
  // The iOS analogue. Xcode's DerivedData is the ~/.gradle of that toolchain — global,
  // so it is left alone for the same reason.
  add(path.join(repoRoot, "apps/mobile/ios/build"), "xcode rebuild");
}

if (withNative) {
  // Not checked in: CNG regenerates both from app.json on the next `pnpm ios`/`pnpm android`.
  add(path.join(repoRoot, "apps/mobile/ios"), "prebuild required");
  add(path.join(repoRoot, "apps/mobile/android"), "prebuild required");
}

if (all) {
  // `.expo/types/router.d.ts` is the typedRoutes declaration and is in mobile's tsconfig
  // `include`. Without it `tsc --noEmit` still passes — it just stops checking route
  // strings — so it is held back from the default clean: a silently weaker typecheck is
  // worse than a stale cache. Metro regenerates it on the next `pnpm start`.
  add(path.join(repoRoot, "apps/mobile/.expo"), "regenerated by pnpm start");
}

// Drop anything already covered by an ancestor that is also queued — `--deps` queues
// node_modules alongside node_modules/.cache, and `--all` queues .expo alongside
// .expo/cache. Left in, each would be measured twice and reported as two removals.
const covered = (abs) =>
  targets.some((other) => other.abs !== abs && abs.startsWith(other.abs + path.sep));
const pruned = targets.filter((t) => !covered(t.abs));
targets.length = 0;
targets.push(...pruned);

// Nothing may be removed from outside the repo except the $TMPDIR caches above, and
// neither root may be removed itself.
function assertSafe(abs) {
  const insideRepo = abs.startsWith(repoRoot + path.sep);
  const insideTmp = abs.startsWith(tmpRoot + path.sep);
  if (!insideRepo && !insideTmp) throw new Error(`refusing to remove outside the repo: ${abs}`);
}

function sizeOf(abs) {
  try {
    const out = execFileSync("du", ["-sk", abs], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    return Number.parseInt(out, 10) * 1024;
  } catch {
    return null; // du is POSIX-only; size reporting is a nicety, not the job
  }
}

const format = (bytes) => {
  const units = ["B", "KB", "MB", "GB"];
  let n = bytes;
  let i = 0;
  while (n >= 1024 && i < units.length - 1) {
    n /= 1024;
    i += 1;
  }
  return `${n < 10 && i > 0 ? n.toFixed(1) : Math.round(n)} ${units[i]}`;
};

const label = (abs) =>
  abs.startsWith(repoRoot + path.sep) ? path.relative(repoRoot, abs) : abs;

if (targets.length === 0 && !withStore) {
  console.log("clean: nothing to remove — already clean.");
  process.exit(0);
}

let freed = 0;
for (const { abs, note } of targets) {
  assertSafe(abs);
  const bytes = sizeOf(abs);
  if (bytes !== null) freed += bytes;
  const suffix = [bytes === null ? null : format(bytes), note].filter(Boolean).join(", ");
  console.log(`${dryRun ? "would remove" : "removed"}  ${label(abs)}${suffix ? `  (${suffix})` : ""}`);
  if (!dryRun) fs.rmSync(abs, { recursive: true, force: true });
}

if (withStore) {
  console.log(`\n${dryRun ? "would run" : "running"}  pnpm store prune`);
  if (!dryRun) spawnSync("pnpm", ["store", "prune"], { cwd: repoRoot, stdio: "inherit" });
}

console.log(
  `\n${dryRun ? "Would free" : "Freed"} ${format(freed)} across ${targets.length} path${targets.length === 1 ? "" : "s"}.`,
);

const next = [
  withDeps && "pnpm install",
  withNative && "pnpm ios / pnpm android (full native rebuild)",
  withGradle && !withNative && "pnpm android (recompiles the NDK/Gradle build)",
  !withDeps && "pnpm api or pnpm typecheck rebuilds shared + db",
].filter(Boolean);
if (next.length > 0) console.log(`Next: ${next.join(" · ")}`);
